version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@sasjs/utils"
    versions:
    - 2.10.1
    - 2.10.3
    - 2.2.0
    - 2.3.0
    - 2.4.0
    - 2.5.1
    - 2.6.1
    - 2.6.2
    - 2.6.5
    - 2.7.0
    - 2.8.1
    - 2.9.0
  - dependency-name: ts-loader
    versions:
    - 8.0.15
    - 8.0.16
    - 8.0.18
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: typedoc
    versions:
    - 0.20.32
    - 0.20.33
    - 0.20.34
  - dependency-name: typescript
    versions:
    - 3.9.8
    - 4.2.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: ts-jest
    versions:
    - 26.5.1
    - 26.5.2
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.4.0
  - dependency-name: isomorphic-fetch
    versions:
    - 3.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
